LibraryBookLoaningSystem/Controllers/WeatherAPIController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Web.Http;
using System.Web.Http.Results;
using LibraryBookLoaningSystem.ViewModels;
using System.Net;
using System.Web.Helpers;
using LibraryBookLoaningSystem.Helpers;
using LibraryBookLoaningSystem.Models;
using System.IO;
using System.Text;

namespace LibraryBookLoaningSystem.Controllers
{
    //[Microsoft.AspNetCore.Components.Route("[controller]")]
    public class WeatherAPIController : Controller
    {
        private readonly string _apiKey = "0e2432c422b08864dd50d8d8b76080ee";

        public WeatherAPIController()
        {
        }

        public ActionResult Index()
        {
            WeatherAPI weatherAPI = AddCities();
            return View(weatherAPI);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public async Task<IActionResult> Index(WeatherAPI weatherAPI, string cities)
        {
            weatherAPI = AddCities();
            if (cities != null)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://api.openweathermap.org");
                    var response = await client.GetAsync($"/data/2.5/weather?id={cities}&appid={_apiKey}&units=metric");
                    //response.EnsureSuccessStatusCode();
                    var stringResult = await response.Content.ReadAsStringAsync();
                    var rawWeather = JsonConvert.DeserializeObject<WeatherData.ResponseWeather>(stringResult);

                    StringBuilder sb = new StringBuilder();
                    sb.Append("<table><tr><th>Weather Description</th></tr>");
                    sb.Append("<tr><td>City:</td><td>" +
                    rawWeather.name + "</td></tr>");
                    //sb.Append("<tr><td>Country:</td><td>" +
                    //rawWeather.sys.country + "</td></tr>");
                    sb.Append("<tr><td>Wind:</td><td>" +
                    rawWeather.wind.speed + " mph</td></tr>");
                    sb.Append("<tr><td>Current Temperature:</td><td>" +
                    rawWeather.main.temp + " °C</td></tr>");
                    sb.Append("<tr><td>Humidity:</td><td>" +
                    rawWeather.main.humidity + "</td></tr>");
                    sb.Append("<tr><td>Weather:</td><td>" +
                    rawWeather.weather[0].description + "</td></tr>");
                    sb.Append("</table>");
                    weatherAPI.apiResponse = sb.ToString();
                }
            }
            return View(weatherAPI);
        }
        public WeatherAPI AddCities()
        {
            WeatherAPI weatherAPI = new WeatherAPI();
            weatherAPI.cities = new Dictionary<string, string>();
            weatherAPI.cities.Add("London", "2643743");
            weatherAPI.cities.Add("Hong Kong", "1819729");
            weatherAPI.cities.Add("Tokyo", "1850147");
            weatherAPI.cities.Add("New York", "5128581");
            weatherAPI.cities.Add("Lisbon", "2267057");
            return weatherAPI;
        }
    }
}

LibraryBookLoaningSystem/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title | Library Book Loaning System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryBookLoaningSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryBookLoaningSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ClientDependency
@inject UserManager<LibraryBookLoaningSystem.IdentityModels.Users> userManager
@{
    var user = userManager.GetUserId(User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Library Book Loaning System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryBookLoaningSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library Book Loaning System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherAPI" asp-action="Index">Weather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Add Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loan" asp-action="Index">Loan Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Return" asp-action="Index" asp-route-userId="@user">Return Books</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div style="" class="card text-center text-white bg-dark">
            <div class="card-header">
                Thank you for visiting
                <p>&copy; @DateTime.Now.Year - LibraryBookLoaningSystem</p>
            </div>
        </div>
    </footer>
    <div style="background-color:#d9534f;">
        <div style="background-color:#292b2c; height:8px; width:450px">
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>